#!/bin/bash

show_git_user_to_register() {
    # Use whiptail to create a menu
    CHOICE=$(whiptail --title "Git User Configuration" \
                      --menu "Choose a user to configure Git" 15 4 \
                      "0" "Aayush Karki" \
                      "1" "Aayush ecobees" \
                      3>&1 1>&2 2>&3)

    # Check the exit status of whiptail
    if [ $? -ne 0 ]; then
        echo "Operation canceled."
        exit 1
    fi

    # Perform actions based on user choice
    case $CHOICE in
        0)
            git config user.name "Aayush Karki"
            git config user.email "aayush.karki022@gmail.com"
            ;;
        1)
            git config user.name "Aayush Karki"
            git config user.email "aayush.ecobees@gmail.com"
            ;;
        *)
            echo "Invalid selection."
            exit 1
            ;;
    esac

    echo "Git user configuration added. $CHOICE"

    git config --list
}

# Execute the menu function
show_git_user_to_register
